name: Atualizar EPG

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  Update-EPG:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout iptv-org/epg repo
        uses: actions/checkout@v4
        with:
          repository: iptv-org/epg
          path: iptv-org-epg

      - name: Install dependencies
        run: cd iptv-org-epg && npm install

      - name: Atualizar epg-pt
        run: |
          cd iptv-org-epg
          npm run grab -- --channels=../EPG/pt.channels.xml --output=../EPG/epg-pt.xml --days=7 --maxConnections=10

      - name: Atualizar epg-meo
        run: |
          cd iptv-org-epg
          npm run grab -- --channels=../EPG/meo.pt.channels.xml --output=../EPG/epg-meo-pt.xml --days=7 --maxConnections=2  # Update this line if needed

      - name: Atualizar epg-nos
        run: |
          cd iptv-org-epg
          npm run grab -- --channels=../EPG/nos.pt.channels.xml --output=../EPG/epg-nos-pt.xml --days=7 --maxConnections=10  # Update this line if needed

      - name: Atualizar epg-rtp
        run: |
          cd iptv-org-epg
          npm run grab -- --site=rtp.pt --output=../EPG/epg-rtp-pt.xml --days=7 --maxConnections=5  # Update this line if needed

      - name: Atualizar epg-rytec
        run: |
          cd EPG
          wget -O epg-rytec-pt.xml.xz "http://www.xmltvepg.nl/rytecPT.xz"

      - name: Compress EPG xml files
        run: |
          cd EPG
          xz -k -f -9 epg*.xml && gzip -k -f -9 epg*.xml

      - name: Remove original EPG xml files
        run: |
          cd EPG
          rm epg*.xml

      - name: Setup Git config
        run: |
          git config user.name "EPG's bot"
          git config user.email "<>"

      - name: Commit changes
        run: |
          git pull
          cd iptv-org-epg
          git add .
          git commit -m "Atualizar EPG's"
          git push origin main
