name: Atualizar EPGs

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  Update-EPGs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Checkout do repositório iptv-org/epg
        uses: actions/checkout@v4
        with:
          repository: iptv-org/epg
          path: iptv-org-epg

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Instalar dependências
        run: |
          cd EPG/scripts
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Atualizar EPGs principais
        run: sh EPG/scripts/epg-pt.sh

      - name: Corrigir EPG da NOS
        run: python EPG/scripts/corrigir_nos.py

      - name: Atualizar lista PlutoTV
        run: |
          cd EPG
          rm -f epg-pluto-tv.xml.gz
          wget -O epg-pluto-tv.xml.gz "https://github.com/matthuisman/i.mjh.nz/raw/refs/heads/master/PlutoTV/all.xml.gz"

      - name: Atualizar lista SamsungTVPlus
        run: |
          cd EPG
          rm -f epg-samsung-tvplus.xml.gz
          wget -O epg-samsung-tvplus.xml.gz "https://github.com/matthuisman/i.mjh.nz/raw/refs/heads/master/SamsungTVPlus/all.xml.gz"

      - name: Atualizar lista RTP
        run: |
          cd EPG
          python scripts/rtp.py

      - name: Atualizar listas RakutenTV
        run: |
          cd EPG/scripts
          python rakuten.py

      - name: Atualizar listas extra
        run: |
          cd EPG/scripts
          python extra.py
          cd -
          cd EPG
          python scripts/ubisofttv.py

      - name: Filtrar EPG do PlutoTV, SamsungTVPlus, RTP e RakutenTV
        run: |
          cd EPG
          python scripts/filter_epg.py

      - name: Substituir EPG original do PlutoTV pelo filtrado
        run: |
          mv EPG/filtered-epg-pluto-tv.xml.gz EPG/epg-pluto-tv.xml.gz

      - name: Substituir EPG original do SamsungTVPlus pelo filtrado
        run: |
          mv EPG/filtered-epg-samsung-tvplus.xml.gz EPG/epg-samsung-tvplus.xml.gz

      - name: Substituir EPG original da RTP pelo filtrado
        run: |
          mv EPG/filtered-epg-rtp-pt.xml.gz EPG/epg-rtp-pt.xml.gz

      - name: Substituir EPG original do RakutenTV pelo filtrado
        run: |
          mv EPG/filtered-epg-rakuten-tv.xml.gz EPG/epg-rakuten-tv.xml.gz

      - name: Configurar Git
        run: |
          git config user.name "EPG's bot"
          git config user.email "<>"

      - name: Commit das atualizações
        run: |
          git pull
          cd EPG && git add .
          git commit -m "Atualizar EPG's"
          git push origin main

  Merge-All-EPGs:
    runs-on: ubuntu-latest
    needs: Update-EPGs
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Configurar Git
        run: |
          git config user.name "EPG's merge bot"
          git config user.email "<>"

      - name: Instalar dependências
        run: |
          cd EPG/scripts
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar merge das EPGs
        run: |
          git pull
          cd EPG
          rm -f all.xml.gz
          cd -
          python EPG/scripts/merge_epg.py

      - name: Commit do merge
        run: |
          git pull
          cd EPG && git add all.xml.gz
          git commit -m "Merge de todas as EPGs"
          git push origin main

  Update-XMLTV-ids:
    runs-on: ubuntu-latest
    needs: Merge-All-EPGs
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Configurar Git
        run: |
          git config user.name "EPG' xmltv-ids bot"
          git config user.email "<>"

      - name: Instalar dependências
        run: |
          cd EPG/scripts
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Alterar xmltv-ids
        run: |
          git pull
          cd EPG
          python scripts/update-xmltv-ids.py

      - name: Validar IDs da lista m3u
        run: |
          xmltv_ids_path="EPG/xmltv-ids.txt"
          sed -i '/^|/d' "$xmltv_ids_path"
          python EPG/scripts/validar-ids-m3u.py

      - name: Commit dos xmltv-ids
        run: |
          git pull
          if ! git diff --quiet; then
            git add EPG/xmltv-ids.txt
            git commit -m "Atualizar xmltv-id's"
            git push origin main
          else
            echo "Nenhuma mudança detectada. Nada a fazer."
          fi
