name: Atualizar EPG
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  Update-EPG:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v4
        
      - name: checkout iptv-org/epg repo
        uses: actions/checkout@v4
        with:
         repository: iptv-org/epg
         path: iptv-org-epg

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Instalar dependências npm
        run: |
          cd /home/runner/work/canaistvpt/canaistvpt/iptv-org-epg
          npm install

      - name: Atualizar EPG PT
        run: |
          cd /home/runner/work/canaistvpt/canaistvpt/iptv-org-epg
          npm run grab -- --channels=../EPG/pt.channels.xml --output=../EPG/epg-pt.xml --days=7 --maxConnections=50
          echo "EPG PT atualizada!"
          sleep 3

      - name: Atualizar EPG MEO
        run: |
          cd /home/runner/work/canaistvpt/canaistvpt/iptv-org-epg
          npm run grab -- --channels=../EPG/meo.pt.channels.xml --output=../EPG/epg-meo-pt.xml --days=7 --maxConnections=50
          echo "EPG da MEO atualizada!"
          sleep 3

      - name: Atualizar EPG NOS
        run: |
          cd /home/runner/work/canaistvpt/canaistvpt/iptv-org-epg
          npm run grab -- --channels=../EPG/nos.pt.channels.xml --output=../EPG/epg-nos-pt.xml --days=7 --maxConnections=50
          echo "EPG da NOS atualizada!"
          sleep 3

      - name: Atualizar EPG RTP
        run: |
          cd /home/runner/work/canaistvpt/canaistvpt/iptv-org-epg
          npm run grab -- --site=rtp.pt --output=../EPG/epg-rtp-pt.xml --days=7 --maxConnections=500
          echo "EPG da RTP atualizada!"
          sleep 3

      - name: Atualizar EPG Plex
        run: |
          cd /home/runner/work/canaistvpt/canaistvpt/iptv-org-epg
          npm run grab -- --channels=../EPG/plex.tv.channels.xml --output=../EPG/epg-plex-tv.xml --days=7 --maxConnections=50
          echo "EPG do Plex atualizada!"
          sleep 3

      - name: Atualizar EPG Rytec
        run: |
          cd ../EPG
          wget -O epg-rytec-pt.xml.xz "http://www.xmltvepg.nl/rytecPT.xz"
          echo "EPG da Rytec atualizada!"
          sleep 3

      - name: Comprimir ficheiros XML da EPG
        run: |
          cd ../EPG
          xz -k -f -9 epg*.xml && gzip -k -f -9 epg*.xml
          echo "Ficheiros comprimidos."
          sleep 3

      - name: Apagar ficheiros XML
        run: |
          cd ../EPG
          rm epg*.xml
          echo "Ficheiros XML apagados!"
          sleep 3

      - name: Atualizar listas Rakuten
        run: | 
          cd EPG/scripts
          python rakuten.py
          
      - name: Atualizar listas FamaTV
        run: | 
          cd EPG/scripts
          python famatv.py
          cd -
          cd EPG
          rm -f epg-fama-pt.xml.xz
          xz -z epg-fama-pt.xml
          
      - name: Atualizar listas Rádios
        run: |
          cd EPG/scripts
          python radios.py
          cd -
          cd EPG
          rm -f epg-radios-pt.xml.xz
          xz -z epg-radios-pt.xml
          
      - name: setup git config
        run: |
          git config user.name "EPG's bot"
          git config user.email "<>"
          
      - name: commit
        run: |
          git pull
          cd EPG && git add .
          git commit -m "Atualizar EPG's"
          git push origin main
