name: Criar EPG para FamaTV

on:
  schedule:
    - cron: '20 */5 * * *' # Executa a cada hora
  workflow_dispatch:

jobs:
  create-epg:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Instalar dependências
      run: |
        sudo apt-get update
        sudo apt-get install -y xz-utils gzip

    - name: Criar arquivo EPG para FamaTV
      run: |
        python3 update_epg.py

    - name: Compactar arquivo em .xz
      run: |
        xz -z epg-fama-pt.xml

    - name: Mover arquivos comprimidos para o diretório EPG
      run: |
        mv epg-fama-pt.xml.xz EPG/

    - name: Verificar modificações do Git
      run: git status

    - name: Commit e Push dos arquivos
      run: |
        git config --global user.name "actions-user"
        git config --global user.email "seu-email@exemplo.com"
        git add EPG/epg-fama-pt.xml.xz EPG/epg-fama-pt.xml.gz
        git commit -m "Criando EPG para FamaTV"
        git push
