name: Atualizar EPG

on:
  schedule:
    - cron: '0 * * * *' # Executa a cada hora

jobs:
  update-epg:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Instalar dependências
      run: |
        sudo apt-get update
        sudo apt-get install -y xz-utils

    - name: Descompactar arquivo EPG
      run: |
        cd EPG
        xz -d -k epg-meo-pt.xml.xz  # Descompacta o arquivo e mantém o original

    - name: Adicionar programação ao FamaTV
      run: |
        python3 update_epg.py

    - name: Compactar novamente o arquivo EPG
      run: |
        cd EPG
        xz -z epg-meo-pt.xml

    - name: Commit e Push alterações
      run: |
        git config --global user.name "EPG's bot"
        git config --global user.email "email@exemplo.com"
        git add epg-meo-pt.xml.xz
        git commit -m "Atualizando EPG com o canal FamaTV"
        git push
