name: Atualizar links e verificá-los
on:
  schedule:
    - cron: '30 */4 * * *'
  workflow_dispatch:

jobs:
  update-stream:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: atualizar links
        run: |
          #!/bin/bash

          file1="m3u8s/cnnpt.m3u8"
          file2="m3u8s/tvi.m3u8"

          for file in "$file1" "$file2"; do
            sed -i "s#wmsAuthSign=[^&]*#wmsAuthSign=$(wget -qO- https://services.iol.pt/matrix?userId -o /dev/null)#g" "$file"
          done
          echo "Ficheiros atualizados."
          exit 0

      - name: setup git config
        run: |
          git config user.name "tvi-pt ch bot"
          git config user.email "<>"

      - name: commit e push
        run: |
          git pull
          git add m3u8s/cnnpt.m3u8
          git add m3u8s/tvi.m3u8
          git commit -m "Atualização automática dos m3u8"
          git push origin main

  test-streams:
    runs-on: ubuntu-latest
    needs: update-stream  # Espera o job anterior terminar
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install -y ffmpeg

      - name: Test Streams
        run: |
          # Verifica se o ficheiro channels-link.txt existe
          if [ ! -f channels-link.txt ]; then
            echo "Error: channels-link.txt not found"
            exit 1
          fi

          # Itera por cada URL no ficheiro channels-link.txt e testa com ffmpeg
          while read stream; do
            echo "Testing stream: $stream"
            if ffmpeg -i "$stream" -t 5 -v error -stats -y -f null -; then
              echo "Stream $stream is working"
            else
              echo "Stream $stream failed"
            fi
          done < channels-link.txt
