name: Update streams
on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  Update-streams:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout
        uses: actions/checkout@v4

      - name: update streams
        run: sh streams.sh

      - name: setup git config
        run: |
          git config user.name "tvi-cnnpt bot"
          git config user.email "<>"

      - name: commit
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git pull
          if [ -n "$(git status --porcelain)" ]; then
            git add *.m3u
            git commit -m "Update streams"
            git push https://$PAT_TOKEN@github.com/thomraider12/canaistvpt.git
          else
            echo "No changes to commit"
          fi
