name: tvi-pt action
on:
  schedule:
    - cron: "0 */2 * * *"
    
  workflow_dispatch:

jobs:
  update-stream:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout
        uses: actions/checkout@v3

      - name: updating tvi-pt
        run: sh streams.sh

      - name: setup git config
        run: |
          git config user.name "tvi-pt bot"
          git config user.email "<>"
      - name: commit
        run: |
          git pull
          git add pt.m3u
          git commit -m "tvi-pt updated"
          git push origin main
