name: Test M3U Streams

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 6 * * *"  # Executa todos os dias às 6:00 UTC

jobs:
  test-streams:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install -y ffmpeg

      - name: Parse M3U file
        id: parse
        run: |
          # Extrai os URLs do ficheiro pt.m3u e guarda num array
          streams=$(grep -oP 'http[^\s]+' pt.m3u)
          echo "streams=$streams" >> $GITHUB_ENV

      - name: Test Streams
        run: |
          # Testa cada URL usando o ffmpeg para verificar se a stream está ativa
          for stream in ${{ env.streams }}; do
            echo "Testing stream: $stream"
            ffmpeg -i "$stream" -t 5 -v error -stats -y -f null - || echo "Stream $stream failed"
          done
