name: Update streams
on:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  Update-streams:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update streams
        run: sh streams.sh

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Commit changes
        run: |
          git pull origin main
          git add *.m3u
          git commit -m "Update streams"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
