name: Update streams
on:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  Update-streams:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout
        uses: actions/checkout@v4

      - name: update streams
        run: sh streams.sh

      - name: setup git config
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: commit
        run: |
          git pull
          git add *.m3u
          git commit -m "Update streams"
          git push origin main
